"""Text formatting of schemas and sample tables for LLM validation prompts."""

from __future__ import annotations

import re
from typing import Any

# Language-agnostic aliases for date/observation-time dimension names.
# These dimensions are auto-generated by the extraction pipeline and must be
# excluded from user-facing validation entirely.
_DATE_NAME_ALIASES: frozenset[str] = frozenset(
    {"date", "дата", "дату", "datum", "fecha", "data", "dt",
     "дата_спостереження", "observation_date", "pub_date", "publication_date"}
)


def is_date_dimension(dim: dict[str, Any]) -> bool:
    """Return True if this dimension is a temporal/date axis that the user cannot edit.

    Matches by dimension type == temporal OR by name alias (any language variant).
    Date dimensions are excluded from validation because they are auto-populated
    by the extraction pipeline and null values in samples are expected and harmless.

    Args:
        dim: Single dimension definition from an OLAP schema.

    Returns:
        True if the dimension should be skipped during validation.
    """
    if str(dim.get("type", "")).strip().lower() == "temporal":
        return True
    normalized = re.sub(r"\W+", "", str(dim.get("name", "") or "").strip().lower())
    return normalized in _DATE_NAME_ALIASES


def strip_date_dimensions(schema: dict[str, Any]) -> dict[str, Any]:
    """Return a shallow copy of the schema with all date/temporal dimensions removed.

    Also removes references to those dimensions from each fact's dimension list
    so the LLM prompt is not confused by dangling references.

    Args:
        schema: Original or proposed OLAP schema.

    Returns:
        Schema dict with temporal dimensions stripped from dimensions list and fact refs.
    """
    dims = [d for d in (schema.get("dimensions") or []) if not is_date_dimension(d)]
    date_names = {
        str(d.get("name", ""))
        for d in (schema.get("dimensions") or [])
        if is_date_dimension(d)
    }

    facts = []
    for fact in schema.get("facts") or []:
        cleaned = dict(fact)
        if isinstance(cleaned.get("dimensions"), list):
            cleaned["dimensions"] = [n for n in cleaned["dimensions"] if n not in date_names]
        facts.append(cleaned)

    return {**schema, "facts": facts, "dimensions": dims}


def strip_date_keys_from_records(records: list[dict[str, Any]], date_dim_names: set[str]) -> list[dict[str, Any]]:
    """Remove date/temporal keys from extracted records before rendering in the prompt.

    Args:
        records: Extracted OLAP record dicts.
        date_dim_names: Set of dimension names to drop (collected from original schema).

    Returns:
        Records with date columns removed.
    """
    if not date_dim_names:
        return records
    return [{k: v for k, v in rec.items() if k not in date_dim_names} for rec in records]


def format_records_as_text(records: list[dict[str, Any]]) -> str:
    """Render OLAP records as a pipe-separated table for the validator prompt.

    Args:
        records: Extracted record dicts (dimension and fact keys as columns).

    Returns:
        Multi-line table text, truncated to 2000 characters.
    """
    if not records:
        return ""
    keys = list(records[0].keys())
    lines = [" | ".join(str(k) for k in keys)]
    for rec in records:
        lines.append(" | ".join(str(rec.get(k, "")) for k in keys))
    return "\n".join(lines)[:2000]


def format_schema(schema: dict[str, Any]) -> str:
    """Render facts and dimensions from a schema as human-readable lines.

    Args:
        schema: OLAP schema with facts and dimensions lists (date dims already stripped).

    Returns:
        Multi-line summary for inclusion in the validation user prompt.
    """
    facts = schema.get("facts", [])
    dimensions = schema.get("dimensions", [])

    lines = ["Facts:"]
    for fact in facts:
        lines.append(f"  - {fact.get('name')}: {fact.get('description')} (unit: {fact.get('unit')})")
        dims = fact.get("dimensions", [])
        if dims:
            lines.append(f"    dimensions: {', '.join(dims)}")

    lines.append("\nDimensions:")
    for dim in dimensions:
        lines.append(f"  - {dim.get('name')}: {dim.get('description')} (type: {dim.get('type')})")
        pv = dim.get("possible_values", [])
        if pv:
            lines.append(f"    values: {', '.join(str(v)[:30] for v in pv[:5])}")

    return "\n".join(lines)


def format_samples(samples: list[dict[str, Any]]) -> str:
    """Render sample article titles and table excerpts for the validator prompt.

    Args:
        samples: List of dicts with title and table_html keys.

    Returns:
        Multi-line sample block for the validation user prompt.
    """
    lines = []
    for i, sample in enumerate(samples, 1):
        lines.append(f"Sample {i}: {sample.get('title', 'Article')}")
        text = sample.get("table_html", "")[:500]
        lines.append(f"  {text}")
    return "\n".join(lines)
