import { useState } from 'react';
import { isAutoDateDimensionName } from '../../../lib/olap/dateDimension';
import { titleCase } from '../../../lib/format';
import type { EditedDimension } from '../types';

interface Props {
  dimensions: EditedDimension[];
  onUpdateDimension: (name: string, updates: Partial<EditedDimension>) => void;
  onAddDimension: (name: string) => void;
  onDeleteDimension: (name: string) => void;
}

export default function DimensionsEditor({
  dimensions,
  onUpdateDimension,
  onAddDimension,
  onDeleteDimension,
}: Props) {
  const [newDimensionName, setNewDimensionName] = useState('');
  const [showNewDimensionInput, setShowNewDimensionInput] = useState(false);

  function handleConfirmAdd() {
    onAddDimension(newDimensionName);
    setNewDimensionName('');
    setShowNewDimensionInput(false);
  }

  return (
    <div className="olap-page__dimension-config" data-testid="olap-dimensions-editor">
      <h3 className="olap-page__schema-title">Dimension configuration</h3>
      <p className="olap-page__schema-subtitle">
        Define dimension metadata once here. For each fact below, select only the needed dimensions.
      </p>

      <button
        type="button"
        className="olap-page__add-schema-btn"
        data-testid="add-dimension-button"
        onClick={() => setShowNewDimensionInput(true)}
      >
        + Add dimension
      </button>

      {showNewDimensionInput && (
        <div className="olap-page__form-group" data-testid="new-dimension-form">
          <label className="olap-page__form-label">
            Dimension name
            <input
              type="text"
              className="olap-page__form-input"
              data-testid="new-dimension-name-input"
              value={newDimensionName}
              placeholder="e.g. Currency"
              onChange={(e) => setNewDimensionName(e.target.value)}
            />
          </label>
          <button
            type="button"
            className="olap-page__btn olap-page__btn--primary"
            data-testid="confirm-add-dimension-button"
            onClick={handleConfirmAdd}
            disabled={!newDimensionName.trim()}
          >
            Save
          </button>
        </div>
      )}

      <div className="olap-page__dimension-editor-list" data-testid="dimension-list">
        {dimensions.map((dimension) => (
          <div
            key={dimension.name}
            className="olap-page__dimension-editor-card"
            data-testid={`dimension-card-${dimension.name}`}
          >
            <div className="olap-page__dimension-editor-head">
              <strong data-testid={`dimension-name-${dimension.name}`}>{titleCase(dimension.name)}</strong>
              {!isAutoDateDimensionName(dimension.name) && (
                <button
                  type="button"
                  className="olap-page__schema-row-delete"
                  data-testid={`delete-dimension-${dimension.name}`}
                  aria-label={`Delete dimension ${dimension.name}`}
                  title="Delete dimension"
                  onClick={() => {
                    if (window.confirm(`Delete dimension "${titleCase(dimension.name)}"?`)) {
                      onDeleteDimension(dimension.name);
                    }
                  }}
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="3 6 5 6 21 6" />
                    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                    <line x1="10" y1="11" x2="10" y2="17" />
                    <line x1="14" y1="11" x2="14" y2="17" />
                  </svg>
                </button>
              )}
              {isAutoDateDimensionName(dimension.name) && (
                <span className="olap-page__dimension-locked-badge">Auto</span>
              )}
            </div>
            {isAutoDateDimensionName(dimension.name) && (
              <div className="olap-page__dimension-locked-note">
                Date dimension is generated by the pipeline automatically and cannot be edited.
              </div>
            )}

            <label className="olap-page__form-label">
              Type
              <input
                type="text"
                className="olap-page__form-input"
                data-testid={`dimension-type-${dimension.name}`}
                value={dimension.type ?? ''}
                disabled={isAutoDateDimensionName(dimension.name)}
                onChange={(e) => onUpdateDimension(dimension.name, { type: e.target.value })}
              />
            </label>

            <label className="olap-page__form-label">
              Description
              <textarea
                className="olap-page__form-textarea"
                value={dimension.description ?? ''}
                disabled={isAutoDateDimensionName(dimension.name)}
                onChange={(e) => onUpdateDimension(dimension.name, { description: e.target.value })}
              />
            </label>

            <label className="olap-page__form-label">
              Possible values (one per line)
              <textarea
                className="olap-page__form-textarea"
                data-testid={`dimension-values-${dimension.name}`}
                value={(dimension.possible_values ?? []).join('\n')}
                disabled={isAutoDateDimensionName(dimension.name)}
                onChange={(e) => {
                  const nextValues = e.target.value
                    .split('\n')
                    .map((value) => value.trim())
                    .filter((value) => value.length > 0);
                  onUpdateDimension(dimension.name, { possible_values: nextValues });
                }}
              />
            </label>
          </div>
        ))}
        {dimensions.length === 0 && (
          <div className="olap-page__empty">No dimensions found in this OLAP schema.</div>
        )}
      </div>
    </div>
  );
}
