"""Persist chart configurations and metadata indexes to MongoDB."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pymongo import UpdateOne
from pymongo.database import Database

from pipeline.config import PipelineConfig


def persist_chart_configs(
    db: Database,
    config: PipelineConfig,
    updates: list[UpdateOne],
    charts_meta: dict[str, dict[str, Any]],
    llm_calls: int,
) -> None:
    """Bulk-write per-subcluster chart configs and update charts_metadata / chart_configs_index.

    Args:
        db: MongoDB database handle.
        config: Collection names for chart storage.
        updates: Bulk write operations for chart_configs collection.
        charts_meta: Nested map of cluster_label -> sc_id -> chart JSON.
        llm_calls: Count of successful LLM chart generations (for api_usage).
    """
    if updates:
        db[config.chart_configs_collection].bulk_write(updates, ordered=False)

    db[config.charts_meta_collection].update_one(
        {"source": "charts_metadata"},
        {
            "$set": {
                "source": "charts_metadata",
                "description": "Index of chart metadata generated from chart-type-selection-v3 schema",
                "schema_version": "3.1",
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "model": f"{config.model_name}:v3-llm",
                "total_configs": len(updates),
                "charts": charts_meta,
            }
        },
        upsert=True,
    )

    db["chart_configs_index"].update_one(
        {"source": "chart_configs_index"},
        {
            "$set": {
                "source": "chart_configs_index",
                "description": "Index of single-chart configurations generated by chart-type-selection-v3 rules",
                "schema_version": "3.1",
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "model": f"{config.model_name}:v3-llm",
                "rag_enabled": False,
                "pdf_sources": [],
                "total_configs": db[config.chart_configs_collection].count_documents({}),
                "api_usage": {
                    "prompt_tokens": 0,
                    "completion_tokens": 0,
                    "total_api_calls": llm_calls,
                },
            }
        },
        upsert=True,
    )
